[tool.ruff]
exclude = [
    '.git',
    '.eggs',
    '__pycache__',
    'doc/examples',
]
ignore = [
    'UP006',
    'UP007',
    'UP009',
    'N802',
    'N806',
    'C901',
    'B008',
    'B011',
    'RUF002',
]
line-length = 100
select = [
    'I',
    'E',
    'F',
    'W',
    'UP',
    'N',
    'C',
    'B',
    'T',
    'RUF',
    'YTT',
]

[tool.ruff.pep8-naming]
ignore-names = [
    'l',
    'h',
]

[dependency-groups]
dev = [
    "bokeh>=3.8.0",
    "coverage>=7.10.6",
    "flake8>=7.3.0",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.6",
    "mypy>=1.18.1",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "pytest>=8.4.2",
    "sambo>=1.25.2",
    "scikit-learn>=1.7.2",
    "tqdm>=4.67.1",
]
